#!/usr/bin/expect

source  ../kernel_config.exp

log_file [log_file_name "$argv0"]

send_user "Starting $argv0\n"

set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated,
# for it is the default value.
# set bootargs 	$bootargs_param0
source ../reboot_kernel.exp

step "Start testing."
sleep 10
set timeout 5
send "\r"
expect -re $kernel_prompt

set case_num 0
set timeout 120

incr case_num
send "/lmbench3/bin/blackfin-Linux/lat_ctx -s 0 processes 2 8 16\r"
while 1 {
    expect {
        -re "size.* ovr.*16 \[0-9\.]+.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send "/lmbench3/bin/blackfin-Linux/lat_ctx -s 16 processes 2 8 16\r"
while 1 {
    expect {
        -re "size.* ovr.*16 \[0-9\.]+.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send "/lmbench3/bin/blackfin-Linux/lat_ctx -s 64 processes 2 8 16\r"
while 1 {
    expect {
        -re "size.* ovr.*16 \[0-9\.]+.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"

log_file
