# TCL File Generated by Component Editor 7.2 on:
# Tue Oct 16 14:57:18 MDT 2007
# DO NOT MODIFY

set_source_file "opencores_i2c.v"
set_module "opencores_i2c"
set_module_description ""
set_module_property "author" ""
set_module_property "className" "opencores_i2c"
set_module_property "displayName" "OpenCores I2C"
set_module_property "group" "Interface Protocols/Serial"
set_module_property "simulationFiles" [ list "i2c_master_bit_ctrl.v" "i2c_master_byte_ctrl.v" "i2c_master_defines.v" "i2c_master_top.v" "opencores_i2c.v" "timescale.v" ]
set_module_property "synthesisFiles" [ list "opencores_i2c.v" "i2c_master_bit_ctrl.v" "i2c_master_byte_ctrl.v" "i2c_master_defines.v" "i2c_master_top.v" "timescale.v" ]
set_module_property "version" "7.2"

# Module parameters

# Interface clock
add_interface "clock" "clock" "sink" "asynchronous"
# Ports in interface clock
add_port_to_interface "clock" "wb_clk_i" "clk"
add_port_to_interface "clock" "wb_rst_i" "reset"

# Interface export_0
add_interface "export_0" "conduit" "start" "clock"
# Ports in interface export_0
add_port_to_interface "export_0" "scl_pad_io" "export"
add_port_to_interface "export_0" "sda_pad_io" "export"

# Interface avalon_slave_0
add_interface "avalon_slave_0" "avalon" "slave" "clock"
set_interface_property "avalon_slave_0" "isNonVolatileStorage" "false"
set_interface_property "avalon_slave_0" "burstOnBurstBoundariesOnly" "false"
set_interface_property "avalon_slave_0" "readLatency" "0"
set_interface_property "avalon_slave_0" "holdTime" "0"
set_interface_property "avalon_slave_0" "printableDevice" "false"
set_interface_property "avalon_slave_0" "readWaitTime" "1"
set_interface_property "avalon_slave_0" "setupTime" "0"
set_interface_property "avalon_slave_0" "addressAlignment" "NATIVE"
set_interface_property "avalon_slave_0" "writeWaitTime" "0"
set_interface_property "avalon_slave_0" "timingUnits" "Cycles"
set_interface_property "avalon_slave_0" "minimumUninterruptedRunLength" "1"
set_interface_property "avalon_slave_0" "isMemoryDevice" "false"
set_interface_property "avalon_slave_0" "linewrapBursts" "false"
set_interface_property "avalon_slave_0" "maximumPendingReadTransactions" "0"
# Ports in interface avalon_slave_0
add_port_to_interface "avalon_slave_0" "wb_adr_i" "address"
add_port_to_interface "avalon_slave_0" "wb_dat_i" "writedata"
add_port_to_interface "avalon_slave_0" "wb_dat_o" "readdata"
add_port_to_interface "avalon_slave_0" "wb_we_i" "write"
add_port_to_interface "avalon_slave_0" "wb_stb_i" "chipselect"
add_port_to_interface "avalon_slave_0" "wb_cyc_i" "chipselect"
add_port_to_interface "avalon_slave_0" "wb_ack_o" "waitrequest_n"

# Interface interrupt_sender
add_interface "interrupt_sender" "interrupt" "sender" "clock"
set_interface_property "interrupt_sender" "associatedAddressablePoint" "avalon_slave_0"
# Ports in interface interrupt_sender
add_port_to_interface "interrupt_sender" "wb_inta_o" "irq"
