# Microtronix SDRAM Assigments Script
# Generated by the Microtronix SDRAM Controller SOPC Builder Perl Script
# Build : 169/9.7.2010

# Open project
project_open -current_revision /data/dwesterg/data/git/BeMicroSDK_MMU/BeMicroSDK.qpf

###
# Misc Assignments
###
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to msdram_ba
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to msdram_a
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to msdram_cs
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to msdram_cas
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to msdram_ras
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to msdram_we


###
# Architecture-Specific Assignments
###
set_instance_assignment -name FAST_OUTPUT_ENABLE_REGISTER ON -to msdram_dq
set_instance_assignment -name FAST_OUTPUT_ENABLE_REGISTER ON -to msdram_dqs
set_instance_assignment -name IO_STANDARD "1.8 V" -to msdram_clk_out_p
set_instance_assignment -name IO_STANDARD "1.8 V" -to msdram_clk_out_n
set_instance_assignment -name IO_STANDARD "1.8 V" -to msdram_ba
set_instance_assignment -name IO_STANDARD "1.8 V" -to msdram_a
set_instance_assignment -name IO_STANDARD "1.8 V" -to msdram_cs
set_instance_assignment -name IO_STANDARD "1.8 V" -to msdram_cas
set_instance_assignment -name IO_STANDARD "1.8 V" -to msdram_ras
set_instance_assignment -name IO_STANDARD "1.8 V" -to msdram_we
set_instance_assignment -name IO_STANDARD "1.8 V" -to msdram_dqm
set_instance_assignment -name IO_STANDARD "1.8 V" -to msdram_dq
set_instance_assignment -name IO_STANDARD "1.8 V" -to msdram_dqs
set_instance_assignment -name IO_STANDARD "1.8 V" -to msdram_cke
set_instance_assignment -name OUTPUT_ENABLE_GROUP 22 -to msdram_dq
set_instance_assignment -name OUTPUT_ENABLE_GROUP 22 -to msdram_dqs
set_instance_assignment -name OUTPUT_ENABLE_GROUP 22 -to msdram_dqm
set_instance_assignment -name PAD_TO_CORE_DELAY 0 -to msdram_dq
set_instance_assignment -name DUAL_PURPOSE_CLOCK_PIN_DELAY 5 -to msdram_dqs
set_global_assignment -name FMAX_REQUIREMENT "133 MHz" -section_id msdram_dqs_clock
set_instance_assignment -name CLOCK_SETTINGS msdram_dqs_clock -to msdram_dqs

# Commit assignments
export_assignments
# Close project
project_close
