#!/usr/bin/expect

source  ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated,
# for it is the default value.
# set bootargs  $bootargs_param0
source ../reboot_kernel.exp

step "Start testing"
sleep 20
send "\r"
expect -re $kernel_prompt
set case_num 0

set timeout 360
incr case_num
send "find /sys/kernel/debug/blackfin/ -type f -print -exec cat \'{}\' \\;\r"
while 1 {
    expect {
        -re "Kernel OOPS|Kernel panic|Hardware Trace" {
            set timeout 20
            expect -re $kernel_prompt
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

all_pass

send_user "Ending $argv0\n"

log_file
