/*
 * This header is generated by sopc2dts
 * Sopc2dts is written by Walter Goossens <waltergoossens@home.nl>
 * in cooperation with the nios2 community <Nios2-dev@sopc.et.ntust.edu.tw>
 */
#ifndef CUSTOM_FPGA_H_
#define CUSTOM_FPGA_H_

/* generated from nios2_bemicro_sopc.sopcinfo */

/* Dumping slaves of cpu_0.data_master*/

/* cpu_0.jtag_debug_module is a altera_nios2 */
#define CONFIG_SYS_CLK_FREQ	100000000
#define CONFIG_SYS_DCACHE_SIZE	4096
#define CONFIG_SYS_DCACHELINE_SIZE	32
#define CONFIG_SYS_ICACHELINE_SIZE	32
#define CONFIG_SYS_EXCEPTION_ADDR	0xd0000020
#define CONFIG_SYS_ICACHE_SIZE	8192
#define CONFIG_SYS_RESET_ADDR	0xc880a000
#define IO_REGION_BASE	0xE0000000

/* slow_periph_bridge.s1 is a altera_avalon_clock_crossing */
/* Dumping slaves of slow_periph_bridge.m1*/

/* sys_timer.s1 is a altera_avalon_timer */
#define CONFIG_SYS_TIMER_IRQ	3
#define CONFIG_SYS_TIMER_FREQ	60000000
#define CONFIG_SYS_TIMER_BASE	0xE8801000

/* led_pio.s1 is a altera_avalon_pio */
#define LED_PIO_BASE	0xE8802000

/* dipsw_pio.s1 is a altera_avalon_pio */
#define DIPSW_PIO_BASE	0xE8803000

/* jtag_uart.avalon_jtag_slave is a altera_avalon_jtag_uart */
#define CONFIG_SYS_JTAG_UART_BASE	0xE8805000

/* sysid.control_slave is a altera_avalon_sysid */
#define CONFIG_SYS_SYSID_BASE	0xE8806000

/* user_pio_pushbtn.s1 is a altera_avalon_pio */
#define USER_PIO_PUSHBTN_BASE	0xE8804000
#define USER_PIO_PUSHBTN_IRQ	7

/* nENET_reg_reset.s1 is a altera_avalon_pio */
#define NENET_REG_RESET_BASE	0xE8807000

/* product_info_0.avalon_slave_0 is a product_info */
#define PRODUCT_INFO_0_BASE	0xE8808000

/* remote_update_blk.s1 is a altera_avalon_remote_update_cycloneiii */
#define REMOTE_UPDATE_BLK_BASE	0xE8809000

/* epcs_flash_controller.epcs_control_port is a altera_avalon_epcs_flash_controller */
#define EPCS_FLASH_CONTROLLER_BASE	0xE880A000
#define EPCS_FLASH_CONTROLLER_IRQ	11

/* EC_GPIO_1.s1 is a altera_avalon_pio */
#define EC_GPIO_1_BASE	0xE880B000

/* EC_GPIO_2.s1 is a altera_avalon_pio */
#define EC_GPIO_2_BASE	0xE880C000

/* nRESET_EXP.s1 is a altera_avalon_pio */
#define NRESET_EXP_BASE	0xE880D000

/* EXP_PRESENT.s1 is a altera_avalon_pio */
#define EXP_PRESENT_BASE	0xE880E000

/* temp_sense_spi.spi_control_port is a altera_avalon_spi */
#define TEMP_SENSE_SPI_BASE	0xE880F000
#define TEMP_SENSE_SPI_IRQ	12

/* mobile_ddr_pipe2.s1 is a altera_avalon_pipeline_bridge */
/* Dumping slaves of mobile_ddr_pipe2.m1*/

/* mobile_ddr_sdram.port_a is a mtx_avalon_sdram */
#define MOBILE_DDR_SDRAM_BASE	0xF0000000

/* ethernet_sd_bridge.s1 is a altera_avalon_clock_crossing */
/* Dumping slaves of ethernet_sd_bridge.m1*/

/* tse_mac.control_port is a triple_speed_ethernet */
#define CONFIG_SYS_ALTERA_TSE_RX_FIFO	1024
#define CONFIG_SYS_ALTERA_TSE_SGDMA_TX_BASE	0xE8001000
#define CONFIG_SYS_ALTERA_TSE_SGDMA_RX_BASE	0xE8003000
#define CONFIG_SYS_ALTERA_TSE_TX_FIFO	1024
#define CONFIG_SYS_ALTERA_TSE_DESC	0xE8000000
#define CONFIG_SYS_ALTERA_TSE_MAC_BASE	0xE8002000
#define CONFIG_ALTERA_TSE
#define CONFIG_MII
#define CONFIG_CMD_MII
#define CONFIG_SYS_ALTERA_TSE_PHY_ADDR 1
#define CONFIG_SYS_ALTERA_TSE_FLAGS 0

/* flash.s1 is a altera_avalon_onchip_memory2 */
#define FLASH_BASE	0xE0001000

/* mmc_spi.spi_control_port is a altera_avalon_spi */
#define MMC_SPI_BASE	0xE0000000
#define MMC_SPI_IRQ	10

#endif	//CUSTOM_FPGA_H_
