#!/usr/bin/expect

source  ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated,
# for it is the default value.
# set bootargs 	$bootargs_param0
source ../reboot_kernel.exp
sleep 10

step "Start testing."

set case_num 0
set case_number1 9
set case_number2 4

set timeout 20
incr case_num
send -s "/bin/fixed_code\r"
while 1 {
    expect {
        -re "(PASS: test_.*\r\n)\{$case_number1\}" {
            case_pass $case_num
            break
        }
        -re "FAIL|fail" {
            case_fail $case_num
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send -s "/bin/fixed_code_p\r"
while 1 {
    expect {
        -re "(PASS: test_.*\r\n)\{$case_number2\}" {
            case_pass $case_num
            break
        }
        -re "FAIL|fail" {
            case_fail $case_num
        }
        timeout {
            case_fail $case_num
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
