#!/usr/bin/expect

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Start testing."
set case_num 0
sleep 2

set SLV_BD_ADDR	"00:15:83:44:C2:E7"
set uart_port   "ttyBF1"

incr case_num
set timeout 15
send "iwrap_boot -b /dev/$uart_port\r"
while 1 {
    expect {
        -re "(\[fF]ail|\[eE]rror).*$kernel_prompt" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send "hcid -n &\r"
while 1 {
    expect {
        -re "(\[dD]one|\[fF]ail|\[eE]rror).*$kernel_prompt" {
            case_fail $case_num
        }
        -re "Bluetooth HCI daemon" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 30
send "hciattach -n /dev/$uart_port bcsp &\r"
while 1 {
    expect {
        -re "(\[dD]one|\[fF]ail|\[eE]rror).*$kernel_prompt" {
            case_fail $case_num
        }
        -re "Starting security manager" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 5
send "hciconfig\r"
while 1 {
    expect {
        -re "(\[dD]one|\[fF]ail|DOWN|not found).*$kernel_prompt" {
            case_fail $case_num
        }
        -re "hci0.*UART.*BD Address: (\[0-9A-F:]+) ACL MTU.*$kernel_prompt" {
            set MST_BD_ADDR $expect_out(1,string)
            send_user "Get BD Address $MST_BD_ADDR\r"
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 5
send "hciconfig hci0 up\r"
while 1 {
    expect {
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

sleep 2

incr case_num
set timeout 300
send "hcitool scan\r"
while 1 {
    expect {
        -re "Inquiry failed: Success|not found" {
            case_fail $case_num
        }
        -re "$SLV_BD_ADDR.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 30
send "hcitool -i hci0 info $SLV_BD_ADDR\r"
sleep 2
while 1 {
    expect {
        -re "not found" {
            case_fail $case_num
        }
        -re "$SLV_BD_ADDR.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
set timeout 20
send "l2ping -i hci0 -c 50 -f $SLV_BD_ADDR\r"
while 1 {
    expect {
        -re "not found|Can't connect:" {
            case_fail $case_num
        }
        -re "50 sent, 50 received, 0% loss" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
