#!/usr/bin/expect

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "$TITLE needs :\n SW5.3: off on bf537 stamp board, ad7147 S4.2 on and other positions off."

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Starting test."
set timeout 8

set case_num 0

incr case_num

send -s "cd /bin\r" 
while 1 {
   expect {
      "root:/bin>" { 
            break
      }

      timeout {                           
         break
         }
     }
}

expect "root:/bin>"
send -s "event_test /dev/input/event0\r" 
while 1 {
   expect {
     -re "Input device name.*Testing" { 
         puts "\nPlease touch the board...\n"	 
	 expect {
		-re "Event: time .* type .* code .* value " { 
                case_pass $case_num
			}
		
		timeout {                           
                case_fail $case_num
			exit
			}
		}
	 sleep 5
	 send "\003"
         break
      }

      timeout {                           
                case_fail $case_num
	exit
         }
     }
}

expect "root:/bin>"
send -s "event_test /dev/input/event1\r" 
while 1 {
   expect {
     -re "Input device name.*Testing" { 
         puts "\nPlease touch the board...\n"	 
	 expect {
		-re "Event: time .* type .* code .* value " { 
                case_pass $case_num
			}
		
		timeout {                           
                case_fail $case_num
			exit
			}
		}
	 sleep 5
	 send "\003"
         break
      }

      timeout {                           
                case_fail $case_num
	exit
         }
     }
}

expect "root:/bin>"
send -s "event_test /dev/input/event2\r" 
while 1 {
   expect {
     -re "Input device name.*Testing" { 
         puts "\nPlease touch the board...\n"	 
	 expect {
		-re "Event: time .* type .* code .* value " { 
                case_pass $case_num
			}
		
		timeout {                           
                case_fail $case_num
			exit
			}
		}
	 sleep 5
	 send "\003"
         break
      }

      timeout {                           
                case_fail $case_num
	exit
         }
     }
}

expect "root:/bin>"
set timeout 50

send_log "\n"
send_log "\n$TITLE ............\[PASS\]\n"

send_user "Ending $argv0\n"
log_file
 

