# TCL File Generated by Altera University Program
# DO NOT MODIFY

# +-----------------------------------
# | module altera_up_avalon_audio
# | 
set_module_property DESCRIPTION "Audio Controller for DE Boards"
set_module_property NAME altera_up_avalon_audio
set_module_property VERSION 8.0.0.1
set_module_property GROUP "University Program/Audio & Video"
set_module_property AUTHOR "Altera University Program"
set_module_property DISPLAY_NAME Audio
set_module_property DATASHEET_URL doc/Altera_UP_Avalon_Audio.pdf
#set_module_property TOP_LEVEL_HDL_FILE Altera_UP_Avalon_Audio.v
set_module_property TOP_LEVEL_HDL_MODULE Altera_UP_Avalon_Audio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
set_module_property GENERATION_CALLBACK generate
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
#add_file Altera_UP_Avalon_Audio.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter audio_in boolean true
set_parameter_property audio_in DISPLAY_NAME "Audio In"
set_parameter_property audio_in GROUP "Audio Direction"
set_parameter_property audio_in UNITS None
set_parameter_property audio_in AFFECTS_PORT_WIDTHS true
set_parameter_property audio_in VISIBLE true
set_parameter_property audio_in ENABLED true

add_parameter audio_out boolean true
set_parameter_property audio_out DISPLAY_NAME "Audio Out"
set_parameter_property audio_out GROUP "Audio Direction"
set_parameter_property audio_out UNITS None
set_parameter_property audio_out AFFECTS_PORT_WIDTHS true
set_parameter_property audio_out VISIBLE true
set_parameter_property audio_out ENABLED true

add_parameter dw int 16
set_parameter_property dw DISPLAY_NAME "Data Width:"
set_parameter_property dw GROUP "Data Format"
set_parameter_property dw UNITS None
set_parameter_property dw AFFECTS_PORT_WIDTHS true
set_parameter_property dw ALLOWED_RANGES {16 20 24 32}
set_parameter_property dw VISIBLE true
set_parameter_property dw ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_audio_slave
# | 
add_interface avalon_audio_slave avalon end
set_interface_property avalon_audio_slave holdTime 0
set_interface_property avalon_audio_slave linewrapBursts false
set_interface_property avalon_audio_slave minimumUninterruptedRunLength 1
set_interface_property avalon_audio_slave bridgesToMaster ""
set_interface_property avalon_audio_slave isMemoryDevice false
set_interface_property avalon_audio_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_audio_slave addressSpan 16
set_interface_property avalon_audio_slave timingUnits Cycles
set_interface_property avalon_audio_slave setupTime 0
set_interface_property avalon_audio_slave writeWaitTime 0
set_interface_property avalon_audio_slave isNonVolatileStorage false
set_interface_property avalon_audio_slave addressAlignment DYNAMIC
set_interface_property avalon_audio_slave readWaitStates 0
set_interface_property avalon_audio_slave maximumPendingReadTransactions 0
set_interface_property avalon_audio_slave readWaitTime 0
set_interface_property avalon_audio_slave readLatency 1
set_interface_property avalon_audio_slave printableDevice false

set_interface_property avalon_audio_slave ASSOCIATED_CLOCK clock_reset

add_interface_port avalon_audio_slave address address Input 2
add_interface_port avalon_audio_slave chipselect chipselect Input 1
add_interface_port avalon_audio_slave read read Input 1
add_interface_port avalon_audio_slave write write Input 1
add_interface_port avalon_audio_slave writedata writedata Input 32
add_interface_port avalon_audio_slave irq dataavailable_n Output 1
add_interface_port avalon_audio_slave readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point external_interface
# | 
add_interface external_interface conduit end

set_interface_property external_interface ASSOCIATED_CLOCK clock_reset

add_interface_port external_interface AUD_ADCDAT export Input 1
add_interface_port external_interface AUD_BCLK export Bidir 1
add_interface_port external_interface AUD_ADCLRCK export Bidir 1
add_interface_port external_interface AUD_DACLRCK export Bidir 1
add_interface_port external_interface AUD_DACDAT export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | Generation function
# | 
proc generate {} {
	send_message info "Starting Generation of Audio Controller"

	# get generation settings
	set language [ get_generation_setting HDL_LANGUAGE ] 
	set outdir [ get_generation_setting OUTPUT_DIRECTORY ] 
	set outname [ get_generation_setting OUTPUT_NAME ] 

	# get perl's path
	set qdr [ get_project_property QUARTUS_ROOTDIR ]
	set perl bin/perl/bin/perl.exe
	set perl "$qdr$perl"
	set perl_include sopc_builder/bin/perl_lib/
	if { [ file executable $perl ] } {
		set perl_include "-I$qdr$perl_include"
	} else {
		# But if it doesn't, maybe it can be found in the path:
		set perl "perl"
		set perl_include ""
	}

	# get parameter values
	set audio_in [ get_parameter_value "audio_in" ]
	set audio_out [ get_parameter_value "audio_out" ]
	set dw [ get_parameter_value "dw" ]
	set bci [ format "5'd%d" [ expr $dw - 1 ] ]

	# set section value
	set use_audio_in	[ format "USE_AUDIO_IN:%d" [ string match "true" $audio_in ] ]
	set use_audio_out	[ format "USE_AUDIO_OUT:%d" [ string match "true" $audio_out ] ]

	# set arguments
	set files "Altera_UP_Avalon_Audio.v;Altera_UP_Audio_Bit_Counter.v;Altera_UP_Audio_In_Deserializer.v;Altera_UP_Audio_Out_Serializer.v;Altera_UP_Clock_Edge.v;Altera_UP_SYNC_FIFO.v"
	set params "AUDIO_DATA_WIDTH:$dw;BIT_COUNTER_INIT:$bci"
	set sections "$use_audio_in;$use_audio_out" 

	# Generate HDL with perl
	exec $perl $perl_include UP_IP_Core_Generator.pl lang=$language dir=$outdir name=$outname files=$files params=$params sections=$sections
}
# | 
# +-----------------------------------

