# TCL File Generated by Component Editor 9.0
# Tue Apr 21 09:34:13 CST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | nand_flash "NAND Flash" v1.0
# | Thomas Chou 2009.04.21.09:34:13
# | simple nand flash io interface
# | 
# +-----------------------------------


# +-----------------------------------
# | module nand_flash
# | 
set_module_property DESCRIPTION "simple nand flash io interface"
set_module_property NAME nand_flash
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Memories and Memory Controllers/Flash"
set_module_property AUTHOR "Thomas Chou"
set_module_property DISPLAY_NAME "NAND Flash"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_tristate_slave
# | 
add_interface avalon_tristate_slave avalon_tristate end
set_interface_property avalon_tristate_slave activeCSThroughReadLatency false
set_interface_property avalon_tristate_slave bridgesToMaster ""
set_interface_property avalon_tristate_slave holdTime 5
set_interface_property avalon_tristate_slave addressAlignment NATIVE
set_interface_property avalon_tristate_slave isMemoryDevice false
set_interface_property avalon_tristate_slave isNonVolatileStorage true
set_interface_property avalon_tristate_slave maximumPendingReadTransactions 0
set_interface_property avalon_tristate_slave printableDevice false
set_interface_property avalon_tristate_slave readLatency 0
set_interface_property avalon_tristate_slave readWaitStates 12
set_interface_property avalon_tristate_slave readWaitTime 12
set_interface_property avalon_tristate_slave setupTime 8
set_interface_property avalon_tristate_slave timingUnits Nanoseconds
set_interface_property avalon_tristate_slave writeWaitStates 12
set_interface_property avalon_tristate_slave writeWaitTime 12

set_interface_property avalon_tristate_slave ENABLED true

add_interface_port avalon_tristate_slave ce_n chipselect_n Input 1
add_interface_port avalon_tristate_slave we_n write_n Input 1
add_interface_port avalon_tristate_slave re_n read_n Input 1
add_interface_port avalon_tristate_slave ale_cle address Input 2
add_interface_port avalon_tristate_slave io data Bidir 8
# | 
# +-----------------------------------
