# TCL File Generated by Component Editor 9.1
# Tue Feb 09 09:40:31 MST 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | oc_spi "SPI Opencore" v9.1
# | GIrving 2010.02.09.09:40:31
# | Standard configurable SPI - Opencores
# | 
# | C:/nevada/3sl150/Nevada_3sl150_SUM_v.020/ip/oc_spi/spi_top.v
# | 
# |    ./spi_clgen.v syn, sim
# |    ./spi_defines.v syn, sim
# |    ./spi_shift.v syn, sim
# |    ./spi_top.v syn, sim
# |    ./timescale.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module oc_spi
# | 
set_module_property DESCRIPTION "Standard configurable SPI - Opencores"
set_module_property NAME oc_spi
set_module_property VERSION 9.1
set_module_property INTERNAL false
set_module_property GROUP "Interface Protocols/Serial"
set_module_property AUTHOR GIrving
set_module_property DISPLAY_NAME "SPI Opencore"
set_module_property TOP_LEVEL_HDL_FILE spi_top.v
set_module_property TOP_LEVEL_HDL_MODULE spi_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file spi_clgen.v {SYNTHESIS SIMULATION}
add_file spi_defines.v {SYNTHESIS SIMULATION}
add_file spi_shift.v {SYNTHESIS SIMULATION}
add_file spi_top.v {SYNTHESIS SIMULATION}
add_file timescale.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter Tp INTEGER 1
set_parameter_property Tp DEFAULT_VALUE 1
set_parameter_property Tp DISPLAY_NAME Tp
set_parameter_property Tp UNITS None
set_parameter_property Tp ALLOWED_RANGES -2147483648:2147483647
set_parameter_property Tp DISPLAY_HINT ""
set_parameter_property Tp AFFECTS_GENERATION false
set_parameter_property Tp HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset wb_clk_i clk Input 1
add_interface_port clock_reset wb_rst_i reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave associatedClock clock_reset
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave wb_dat_i writedata Input 32
add_interface_port avalon_slave wb_dat_o readdata Output 32
add_interface_port avalon_slave wb_sel_i writebyteenable Input 4
add_interface_port avalon_slave wb_we_i read_n Input 1
add_interface_port avalon_slave wb_stb_i chipselect Input 1
add_interface_port avalon_slave wb_ack_o waitrequest_n Output 1
add_interface_port avalon_slave wb_adr_i address Input 5
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_export
# | 
add_interface conduit_export conduit end

set_interface_property conduit_export ASSOCIATED_CLOCK clock_reset
set_interface_property conduit_export ENABLED true

add_interface_port conduit_export wb_err_o export Output 1
add_interface_port conduit_export ss_pad_o export Output 8
add_interface_port conduit_export sclk_pad_o export Output 1
add_interface_port conduit_export mosi_pad_o export Output 1
add_interface_port conduit_export miso_pad_i export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt
# | 
add_interface interrupt interrupt end
set_interface_property interrupt associatedAddressablePoint avalon_slave

set_interface_property interrupt ASSOCIATED_CLOCK clock_reset
set_interface_property interrupt ENABLED true

add_interface_port interrupt wb_int_o irq Output 1
# | 
# +-----------------------------------
