# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


#if 0


SHELL = /bin/sh

srcdir = ../.././libgui/src
top_srcdir = ../.././libgui
VPATH = ../.././libgui/src
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/libgui
pkglibdir = $(libdir)/libgui
pkgincludedir = $(includedir)/libgui

top_builddir = ..

ACLOCAL = /home/dwesterg/data/nios2-linux/nios2-linux/insight/missing aclocal-1.4
AUTOCONF = autoconf
AUTOMAKE = /home/dwesterg/data/nios2-linux/nios2-linux/insight/missing automake-1.4
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = /usr/bin/install -c $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = /usr/bin/install -c -m 644
INSTALL_SCRIPT = /usr/bin/install -c
transform = s,y,y,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
AR = ar
BFDHDIR = @BFDHDIR@
BFDLIB = @BFDLIB@
CC = gcc
CXX = @CXX@
CXXCPP = @CXXCPP@
DEJAGNUHDIR = @DEJAGNUHDIR@
DEJAGNULIB = @DEJAGNULIB@
DEVOHDIR = @DEVOHDIR@
ENDIAN = @ENDIAN@
EXEEXT = 
GUILIB = @GUILIB@
HAVE_DEVO_SIM = @HAVE_DEVO_SIM@
IDEHDIR = @IDEHDIR@
IDELIB = @IDELIB@
IDETCLLIB = @IDETCLLIB@
ILUHDIR = @ILUHDIR@
ILULIB = @ILULIB@
ILUTOP = @ILUTOP@
INTLHDIR = @INTLHDIR@
INTLLIB = @INTLLIB@
ITCLHDIR = @ITCLHDIR@
ITCLLIB = @ITCLLIB@
ITCLMKIDX = @ITCLMKIDX@
ITCLSH = @ITCLSH@
ITCL_BUILD_LIB_SPEC = @ITCL_BUILD_LIB_SPEC@
ITCL_LIB_FILE = @ITCL_LIB_FILE@
ITCL_LIB_FULL_PATH = @ITCL_LIB_FULL_PATH@
ITCL_SH = $$here/$(top_builddir)/../itcl/itcl/unix/itcl_sh$(EXEEXT)
ITK_BUILD_LIB_SPEC = @ITK_BUILD_LIB_SPEC@
ITK_LIB_FILE = @ITK_LIB_FILE@
ITK_LIB_FULL_PATH = @ITK_LIB_FULL_PATH@
LIBERTY = @LIBERTY@
LIBGCC = @LIBGCC@
LIBGUIHDIR = @LIBGUIHDIR@
LIBGUILIB = @LIBGUILIB@
LIBGUI_LIBRARY_DIR = /home/dwesterg/data/nios2-linux/nios2-linux/insight/libgui/library
LIBIBERTY = @LIBIBERTY@
MAINT = #
MAKEINFO = makeinfo
OBJEXT = o
OPCODESLIB = @OPCODESLIB@
PACKAGE = libgui
RANLIB = ranlib
RPATH_ENVVAR = LD_LIBRARY_PATH
RUNTESTDIR = @RUNTESTDIR@
SIMHDIR = @SIMHDIR@
SIMLIB = @SIMLIB@
TCLCONFIG = /data/dwesterg/nios2-linux/nios2-linux/insight/tcl/unix/tclConfig.sh
TCLHDIR = -I/data/dwesterg/nios2-linux/nios2-linux/insight/tcl/generic
TCL_BIN_DIR = 
TCL_BUILD_LIB_SPEC = -L/home/dwesterg/data/nios2-linux/nios2-linux/insight/tcl/unix -ltcl8.4${TCL_DBGX}
TCL_CFLAGS = 
TCL_DEFS = -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -D_LARGEFILE64_SOURCE=1 -DTCL_WIDE_INT_IS_LONG=1 -DHAVE_GETCWD=1 -DHAVE_OPENDIR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_STRTOLL=1 -DHAVE_STRTOULL=1 -DHAVE_TMPNAM=1 -DHAVE_WAITPID=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DUSE_TERMIOS=1 -DHAVE_SYS_TIME_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_STRUCT_TM_TM_ZONE=1 -DHAVE_TM_ZONE=1 -DHAVE_GMTIME_R=1 -DHAVE_LOCALTIME_R=1 -DHAVE_TM_GMTOFF=1 -DHAVE_TIMEZONE_VAR=1 -DHAVE_STRUCT_STAT_ST_BLKSIZE=1 -DHAVE_ST_BLKSIZE=1 -DHAVE_SIGNED_CHAR=1 -DHAVE_LANGINFO=1 -DSTATIC_BUILD=1 -DPEEK_XCLOSEIM=1 -DHAVE_SYS_IOCTL_H=1 
TCL_LD_FLAGS = -rdynamic
TCL_LD_SEARCH_FLAGS = -Wl,-rpath,${LIB_RUNTIME_DIR}
TCL_LIBRARY = /data/dwesterg/nios2-linux/nios2-linux/insight/tcl/library
TCL_LIBS = -ldl  -lieee -lm
TCL_LIB_FILE = libtcl8.4${TCL_DBGX}.a
TCL_LIB_FULL_PATH = 
TCL_LIB_SPEC = -L/usr/local/lib -ltcl8.4${TCL_DBGX}
TCL_RANLIB = ranlib
TCL_SHLIB_CFLAGS = -fPIC
TCL_SHLIB_LD = gcc -pipe -shared
TIXHDIR = @TIXHDIR@
TIX_BUILD_LIB_SPEC = @TIX_BUILD_LIB_SPEC@
TIX_LIB_FULL_PATH = @TIX_LIB_FULL_PATH@
TKCONFIG = /data/dwesterg/nios2-linux/nios2-linux/insight/tk/unix/tkConfig.sh
TKHDIR = -I/data/dwesterg/nios2-linux/nios2-linux/insight/tk/generic
TK_BUILD_INCLUDES = 
TK_BUILD_LIB_SPEC = -L/home/dwesterg/data/nios2-linux/nios2-linux/insight/tk/unix -ltk8.4
TK_DEFS = -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -D_LARGEFILE64_SOURCE=1 -DTCL_WIDE_INT_IS_LONG=1 -DSTATIC_BUILD=1 -DPEEK_XCLOSEIM=1 -DHAVE_SYS_TIME_H=1 -DTIME_WITH_SYS_TIME=1 -DHAVE_PW_GECOS=1 
TK_LIBS = -lX11 -ldl  -lieee -lm
TK_LIB_FILE = libtk8.4.a
TK_LIB_FULL_PATH = 
TK_LIB_SPEC = -L/usr/local/lib -ltk8.4
TK_VERSION = 8.4
TK_XINCLUDES = 
TK_XLIBSW = -lX11
VERSION = 0.0
ac_cv_c_itclsh = @ac_cv_c_itclsh@

AUTOMAKE_OPTIONS = cygnus

noinst_LIBRARIES = libgui.a

#include_HEADERS = #\
#	guitcl.h subcommand.h

datadir = ${prefix}/share
guidir = $(datadir)/redhat/gui

TBL_MAJOR_VERSION = 2
TBL_MINOR_VERSION = 7
TBL_VERSION = $(TBL_MAJOR_VERSION).$(TBL_MINOR_VERSION)

# tkTable version info

# This sets the name that tkTable will define for itself when loaded
# If you change this, then the demos won't work, but it might be necessary
# for those with another built-in "table" command
TBL_COMMAND = table

LIBGUI_CFLAGS = 

INCLUDES = $(LIBGUI_CFLAGS) $(TCLHDIR) \
$(TKHDIR) \
$(TK_XINCLUDES) $(TCL_DEFS) $(TK_DEFS) \
$(TKHDIR)/../unix $(TKHDIR)/../win \
-DTBL_VERSION=\"$(TBL_VERSION)\"\
-DTBL_COMMAND=\"$(TBL_COMMAND)\"\
-DTBL_RUNTIME=\"tkTable.tcl\" -DTBL_RUNTIME_DIR=\"$(guidir)\"\
-DSTATIC_BUILD


TKTABLE_SOURCES = tkTable.c tkTableCell.c tkTableCellSort.c \
tkTableCmds.c tkTableEdit.c tkTableTag.c tkTableWin.c tkTableUtil.c


libgui_a_SOURCES = guitcl.h subcommand.c subcommand.h \
tclwinprint.c tclshellexe.c paths.c \
tclwingrab.c tclwinpath.c tclmsgbox.c tclcursor.c \
tkWinPrintText.c tkWinPrintCanvas.c tkWarpPointer.c $(TKTABLE_SOURCES)

mkinstalldirs = $(SHELL) $(top_srcdir)/../mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
LIBRARIES =  $(noinst_LIBRARIES)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I..
CPPFLAGS = 
LDFLAGS = 
LIBS = 
libgui_a_LIBADD = 
libgui_a_OBJECTS =  subcommand.$(OBJEXT) tclwinprint.$(OBJEXT) \
tclshellexe.$(OBJEXT) paths.$(OBJEXT) tclwingrab.$(OBJEXT) \
tclwinpath.$(OBJEXT) tclmsgbox.$(OBJEXT) tclcursor.$(OBJEXT) \
tkWinPrintText.$(OBJEXT) tkWinPrintCanvas.$(OBJEXT) \
tkWarpPointer.$(OBJEXT) tkTable.$(OBJEXT) tkTableCell.$(OBJEXT) \
tkTableCellSort.$(OBJEXT) tkTableCmds.$(OBJEXT) tkTableEdit.$(OBJEXT) \
tkTableTag.$(OBJEXT) tkTableWin.$(OBJEXT) tkTableUtil.$(OBJEXT)
CFLAGS = -g -O2
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
HEADERS =  $(include_HEADERS)

DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
SOURCES = $(libgui_a_SOURCES)
OBJECTS = $(libgui_a_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .o .obj .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) $(srcdir)/tkTable_version.in
	cd $(top_srcdir) && $(AUTOMAKE) --cygnus src/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-noinstLIBRARIES:

clean-noinstLIBRARIES:
	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)

distclean-noinstLIBRARIES:

maintainer-clean-noinstLIBRARIES:

.c.o:
	$(COMPILE) -c $<

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

libgui.a: $(libgui_a_OBJECTS) $(libgui_a_DEPENDENCIES)
	-rm -f libgui.a
	$(AR) cru libgui.a $(libgui_a_OBJECTS) $(libgui_a_LIBADD)
	$(RANLIB) libgui.a

install-includeHEADERS: $(include_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(includedir)
	@list='$(include_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	  echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(includedir)/$$p"; \
	  $(INSTALL_DATA) $$d$$p $(DESTDIR)$(includedir)/$$p; \
	done

uninstall-includeHEADERS:
	@$(NORMAL_UNINSTALL)
	list='$(include_HEADERS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(includedir)/$$p; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = src

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am:
check: check-am
installcheck-am:
installcheck: installcheck-am
install-info-am: 
install-info: install-info-am
install-exec-am: install-exec-local
install-exec: install-exec-am

install-data-am: install-includeHEADERS
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-includeHEADERS
uninstall: uninstall-am
all-am: Makefile $(LIBRARIES) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(includedir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-noinstLIBRARIES mostlyclean-compile \
		mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-noinstLIBRARIES clean-compile clean-tags clean-generic \
		mostlyclean-am

clean: clean-am

distclean-am:  distclean-noinstLIBRARIES distclean-compile \
		distclean-tags distclean-generic clean-am

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-noinstLIBRARIES \
		maintainer-clean-compile maintainer-clean-tags \
		maintainer-clean-generic distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-noinstLIBRARIES distclean-noinstLIBRARIES \
clean-noinstLIBRARIES maintainer-clean-noinstLIBRARIES \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile uninstall-includeHEADERS \
install-includeHEADERS tags mostlyclean-tags distclean-tags clean-tags \
maintainer-clean-tags distdir info-am info dvi-am dvi check check-am \
installcheck-am installcheck install-info-am install-info \
install-exec-local install-exec-am install-exec install-data-am \
install-data install-am install uninstall-am uninstall all-redirect \
all-am all installdirs mostlyclean-generic distclean-generic \
clean-generic maintainer-clean-generic clean mostlyclean distclean \
maintainer-clean

#endif
#define TBL_MAJOR_VERSION 2
#define TBL_MINOR_VERSION 7
#define TBL_VERSION "2.7"

tkTable.tcl.h: $(srcdir)/tkTable.tcl
	sed -e '/^$\#/d' -e '/^$$/d' -e 's/\"/\\"/g' -e 's/^/"/' -e 's/$$/\\n"/' <$(srcdir)/tkTable.tcl >tkTable.tcl.h || rm tkTable.tcl.h 

# Defining lib_LIBRARIES conditionally doesn't do the right thing.
install-exec-local:
#	@$(NORMAL_INSTALL)
#	$(mkinstalldirs) $(libdir)
#	$(INSTALL_DATA) libgui.a $(libdir)/libgui.a
#	@$(POST_INSTALL)
#	$(RANLIB) $(libdir)/libgui.a

paths.$(OBJEXT): paths.c guitcl.h
subcommand.$(OBJEXT): subcommand.c subcommand.h
tkCanvEdge.$(OBJEXT): tkCanvEdge.c ../config.h
tkCanvLayout.$(OBJEXT): tkCanvLayout.c ../config.h tkCanvLayout.h
tkGraphCanvas.$(OBJEXT): tkGraphCanvas.c tkCanvLayout.h
xpmlib.$(OBJEXT): xpmlib.c guitcl.h
assertions.$(OBJEXT): assertions.c ../config.h assertions.h
tclcursor.$(OBJEXT): tclcursor.c ../config.h guitcl.h subcommand.h
tclhelp.$(OBJEXT): tclhelp.c ../config.h guitcl.h subcommand.h
tclgetdir.$(OBJEXT): tclgetdir.c guitcl.h
tclmain.$(OBJEXT): tclmain.c guitcl.h
tclwinprint.$(OBJEXT): tclwinprint.c guitcl.h subcommand.h
tclsizebox.$(OBJEXT): tclsizebox.c guitcl.h
tclshellexe.$(OBJEXT): tclshellexe.c guitcl.h
tclmapi.$(OBJEXT): tclmapi.c guitcl.h subcommand.h
tclwinfont.$(OBJEXT): tclwinfont.c guitcl.h
tclwingrab.$(OBJEXT): tclwingrab.c guitcl.h
tclwinpath.$(OBJEXT): tclwinpath.c guitcl.h subcommand.h
tclwinmode.$(OBJEXT): tclwinmode.c guitcl.h
tkTable.$(OBJEXT): tkTable.c tkTable.h tkTableInitScript.h tkTable.tcl.h
tkTableCell.$(OBJEXT): tkTableCell.c tkTable.h
tkTableCellSort.$(OBJEXT): tkTableCellSort.c tkTable.h
tkTableCmds.$(OBJEXT): tkTableCmds.c tkTable.h
tkTableEdit.$(OBJEXT): tkTableEdit.c tkTable.h
tkTableTag.$(OBJEXT): tkTableTag.c tkTable.h
tkTablePs.$(OBJECT): tkTablePs.c tkTable.h
tkTableWin.$(OBJEXT):tkTableWin.c  tkTable.h
tkTableUtil.$(OBJEXT): tkTableUtil.c tkTable.h
tkTable.tcl.h: tkTable.tcl

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
