#!/usr/bin/expect

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Starting test."
set case_num 0
sleep 5

set timeout 8
incr case_num
send -s "modprobe bf54x-keys\r"
while 1 {
    expect {
        -re "input.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send -s "lsmod\r"
while 1 {
    expect {
        -re "bf54x_keys.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

sleep 2
set timeout 10
incr case_num
send -s "event_test /dev/input/event0\r"
while 1 {
    expect {
        -re "Input device name.*bf54x-keys.*Testing" {
            send_user "\nPlease hit button \"1\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(1\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"2\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(2\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"3\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(3\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"4\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(4\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"5\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(5\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"6\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(6\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"7\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(7\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"8\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(8\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"9\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(9\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"0\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(0\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"UP ARROW\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(Up\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"DOWN ARROW\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(Down\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"2ND\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(Tab\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"CLEAR\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(Backspace\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"HELP\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(Help\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            incr case_num
            send_user "\nPlease hit button \"ENTER\" on keyboard...\n"
            expect {
                -re "Event: time .* type .* code.*\\\(Enter\\\).*value.*\r\n.*\r\n.*\r\n.*\r\n" {
                    case_pass $case_num
                }
                timeout {
                    case_fail $case_num
                }
            }

            send "\003"
            expect -re $kernel_prompt
            break
        }

        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send -s "rmmod bf54x_keys\r"
while 1 {
    expect {
        -nocase -re "(fail|error|rmmod:).*$kernel_prompt" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send -s "lsmod\r"
while 1 {
    expect {
        -re "bf54x_keys.*$kernel_prompt" {
            case_fail $case_num
        }
        -re $kernel_prompt {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
