#!/usr/bin/expect

source ../kernel_config.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Spawn kermit"
source ../spawn_kermit.exp

step "Reboot the kernel."
# To add following line here to indicate that if the bootargs is different,
# it could be set here. If the bootargs value is 0, it needn't be stated,
# for it is the default value.
# set bootargs  $bootargs_param0
source ../reboot_kernel.exp

step "Start testing."
set case_num 0

set timeout 5
expect -re $kernel_prompt

if { $board_type == "BF548-EZKIT" } {
    set i2c_num "1"
} else {
    set i2c_num "0"
}

set timeout 8
incr case_num
send "twilcd_userspace_test -h\r"
while 1 {
    expect {
        -re "Usage.*$kernel_prompt" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

set timeout 5
incr case_num
send "twilcd_userspace_test -n $i2c_num -p 0 \"Hello World!\"\r"
while 1 {
    expect {
        "Message" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

set timeout 10
send_user "Have you seen \"Hello World!\" on left side of LCD screen?\nIf true, type y; if false, type n:"
while 1 {
    expect_user {
        -re "\[nN]" {
            case_fail $case_num
        }
        -re "\[yY]" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

incr case_num
send "twilcd_userspace_test -n $i2c_num -p 5 \"\`date\`\"\r"
while 1 {
    expect {
        "Message" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

set timeout 10
send_user "Have you seen date info on center of LCD screen?\nIf true, type y; if false, type n:"
while 1 {
    expect_user {
        -re "\[nN]" {
            case_fail $case_num
        }
        -re "\[yY]" {
            case_pass $case_num
            break
        }
        timeout {
            case_fail $case_num
        }
    }
}

all_pass
send_user "Ending $argv0\n"
log_file
