# TCL File Generated by Component Editor on: 
# Mon Jun 18 15:35:38 CST 2007
# DO NOT MODIFY

set_source_file "irqn.v"
set_module "irqn"
set_module_description ""
set_module_property instantiateInSystemModule true
set_module_property version "1.0"
set_module_property group "Other"
set_module_property editable true

# Module parameters

# Clock Interface global_signals_clock
add_clock_interface "global_signals_clock" 
set_interface_property "global_signals_clock" "externallyDriven" "false"
set_interface_property "global_signals_clock" "clockRateKnown" "false"
set_interface_property "global_signals_clock" "clockRate" "0"
# Ports in interface global_signals_clock
add_port_to_interface "global_signals_clock" "gls_clk" "clk"
add_port_to_interface "global_signals_clock" "gls_reset_n" "reset_n"

# Interface s0
add_interface "s0" "avalon" "slave" "global_signals_clock"
set_interface_property "s0" "isNonVolatileStorage" "false"
set_interface_property "s0" "burstOnBurstBoundariesOnly" "false"
set_interface_property "s0" "transparentBridge" "false"
set_interface_property "s0" "readLatency" "0"
set_interface_property "s0" "readWaitStates" "1"
set_interface_property "s0" "isFlash" "false"
set_interface_property "s0" "holdTime" "0"
set_interface_property "s0" "printableDevice" "false"
set_interface_property "s0" "registerIncomingSignals" "false"
set_interface_property "s0" "readWaitTime" "1"
set_interface_property "s0" "setupTime" "0"
set_interface_property "s0" "addressGroup" "0"
set_interface_property "s0" "interleaveBursts" "false"
set_interface_property "s0" "addressAlignment" "NATIVE"
set_interface_property "s0" "isBigEndian" "false"
set_interface_property "s0" "writeLatency" "0"
set_interface_property "s0" "writeWaitTime" "0"
set_interface_property "s0" "timingUnits" "Cycles"
set_interface_property "s0" "minimumUninterruptedRunLength" "1"
set_interface_property "s0" "registerOutgoingSignals" "false"
set_interface_property "s0" "addressSpan" "1"
set_interface_property "s0" "isMemoryDevice" "false"
set_interface_property "s0" "linewrapBursts" "false"
set_interface_property "s0" "alwaysBurstMaxBurst" "false"
set_interface_property "s0" "writeWaitStates" "0"
set_interface_property "s0" "maximumPendingReadTransactions" "0"
set_interface_property "s0" "wellBehavedWaitrequest" "false"
# Ports in interface s0
add_port_to_interface "s0" "avs_s0_write" "write"
add_port_to_interface "s0" "avs_s0_writedata" "writedata"

# IRQ Interface s0_irq
add_interface "s0_irq" "interrupt" "sender" "global_signals_clock"
set_interface_property "s0_irq" "irqScheme" "NONE"
set_interface_property "s0_irq" "associatedAddressablePoint" "s0"
# Ports in interface s0_irq
add_port_to_interface "s0_irq" "avs_s0_irq" "irq"

# Wire Interface s0_export
add_interface "s0_export" "conduit" "output" "global_signals_clock"
# Ports in interface s0_export
add_port_to_interface "s0_export" "avs_s0_export_irqn" "export"
