# TCL File Generated by Component Editor 8.0
# Tue Jul 15 01:53:17 EDT 2008
# DO NOT MODIFY


# +-----------------------------------
# | 
# | dummy_master "Dummy Master" v1.0
# | RSF 2008.07.15.01:53:17
# | This master can be used to terminate the PLL peripheral and avoid a clock adapter.  Or other such situations.
# | 
# | C:/work/rod_designs/programmable_test_master/ip/dummy_master/dummy_master.v
# | 
# |    ./dummy_master.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module dummy_master
# | 
set_module_property DESCRIPTION "This master can be used to terminate the PLL peripheral and avoid a clock adapter.  Or other such situations."
set_module_property NAME dummy_master
set_module_property VERSION 1.0
set_module_property GROUP "Peripherals/Debug and Performance"
set_module_property AUTHOR RSF
set_module_property DISPLAY_NAME "Dummy Master"
set_module_property TOP_LEVEL_HDL_FILE dummy_master.v
set_module_property TOP_LEVEL_HDL_MODULE dummy_master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file dummy_master.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter MASTER_ADDRESS_WIDTH int 8
set_parameter_property MASTER_ADDRESS_WIDTH DISPLAY_NAME MASTER_ADDRESS_WIDTH
set_parameter_property MASTER_ADDRESS_WIDTH UNITS None
set_parameter_property MASTER_ADDRESS_WIDTH AFFECTS_PORT_WIDTHS true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point master_clk
# | 
add_interface master_clk clock end
set_interface_property master_clk ptfSchematicName ""

add_interface_port master_clk csi_master_clk_clk clk Input 1
add_interface_port master_clk csi_master_clk_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point m0
# | 
add_interface m0 avalon start
set_interface_property m0 linewrapBursts false
set_interface_property m0 adaptsTo ""
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 burstOnBurstBoundariesOnly false

set_interface_property m0 ASSOCIATED_CLOCK master_clk

add_interface_port m0 avm_m0_address address Output -1
add_interface_port m0 avm_m0_byteenable byteenable Output 4
add_interface_port m0 avm_m0_read read Output 1
add_interface_port m0 avm_m0_write write Output 1
add_interface_port m0 avm_m0_writedata writedata Output 32
add_interface_port m0 avm_m0_waitrequest waitrequest Input 1
add_interface_port m0 avm_m0_readdata readdata Input 32
# | 
# +-----------------------------------
