# TCL File Generated by Component Editor 9.0
# Thu Apr 23 11:35:45 CST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | gpio "gpio" v1.0
# | Thomas Chou 2009.04.23.11:35:45
# | generic gpio
# | 
# | /home/thomas/new2/gpio/t1proj/gpio.v
# | 
# |    ./gpio.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module gpio
# | 
set_module_property DESCRIPTION "generic gpio"
set_module_property NAME gpio
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "Peripherals/Microcontroller Peripherals"
set_module_property AUTHOR "Thomas Chou"
set_module_property DISPLAY_NAME gpio
set_module_property TOP_LEVEL_HDL_FILE hdl/gpio.v
set_module_property TOP_LEVEL_HDL_MODULE gpio
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file hdl/gpio.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter GPIO_WIDTH INTEGER 8
set_parameter_property GPIO_WIDTH DISPLAY_NAME GPIO_WIDTH
set_parameter_property GPIO_WIDTH UNITS None
set_parameter_property GPIO_WIDTH DISPLAY_HINT ""
set_parameter_property GPIO_WIDTH AFFECTS_GENERATION false
set_parameter_property GPIO_WIDTH IS_HDL_PARAMETER true
add_parameter GPIO_ADDR INTEGER 3
set_parameter_property GPIO_ADDR DISPLAY_NAME GPIO_ADDR
set_parameter_property GPIO_ADDR UNITS None
set_parameter_property GPIO_ADDR DISPLAY_HINT ""
set_parameter_property GPIO_ADDR AFFECTS_GENERATION false
set_parameter_property GPIO_ADDR IS_HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment NATIVE
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 readdata readdata Output 2
add_interface_port avalon_slave_0 address address Input -1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 writedata writedata Input 2
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end bidir_port export Bidir -1
# | 
# +-----------------------------------
