#!/usr/bin/expect

source ../kernel_config.exp
source ../board_info.exp
log_file [log_file_name "$argv0"]
send_user "Starting $argv0\n"
set TITLE [title "$argv0"]

step "Start kermit."
source ../spawn_kermit.exp

step "Reboot the kernel."
source ../reboot_kernel.exp

step "Starting test"
set case_num 0

incr case_num
set timeout 15
send "event_test /dev/input/event0\r"
while 1 {
   expect {
       -re "Input device name.*gpio-keys.*Testing" {
           send_user "\nPlease hit the PB1 buttons on the board...\n"
           expect {
               -re  "Event: time .* type .* code 256.* value.*\r\n.*\r\n.*\r\n.*\r\n" {
                   case_pass $case_num
               }
               timeout {
                   case_fail $case_num
               }
           }

           incr case_num
           send_user "\nPlease hit the PB2 buttons on the board...\n"
           expect {
               -re "Event: time .* type .* code 257.* value.*\r\n.*\r\n.*\r\n.*\r\n" {
                   case_pass $case_num
               }
               timeout {
                   case_fail $case_num
               }
           }

           incr case_num
           send_user "\nPlease hit the PB3 buttons on the board...\n"
           expect {
               -re "Event: time .* type .* code 258.* value.*\r\n.*\r\n.*\r\n.*\r\n" {
                   case_pass $case_num
               }
               timeout {
                   case_fail $case_num
               }
           }

           if { $board_type == "BF537-STAMP" } {
               incr case_num
               send_user "\nPlease hit the PB4 buttons on the board...\n"
               expect {
                   -re "Event: time .* type .* code 259.* value.*\r\n.*\r\n.*\r\n.*\r\n" {
                       case_pass $case_num
                   }
                   timeout {
                       case_fail $case_num
                   }
               }
           }

           break
       }

       timeout {
           case_fail $case_num
       }
   }
}

send -s "\3"
expect ">"
 
all_pass
send_user "Ending $argv0\n"
log_file
