lib-y = memset.o memcpy.o memmove.o

lib-y += ashldi3.o
lib-y += ashrdi3.o
lib-y += cmpdi2.o
lib-y += lshrdi3.o
lib-y += muldi3.o
lib-y += mulsi3.o
lib-y += negdi2.o
lib-y += ucmpdi2.o
lib-y += libgcc.o
