# Pin & Location Assignments
# ==========================
set_location_assignment PIN_AH15 -to clkin_50
set_location_assignment PIN_A14 -to clkin_125
set_location_assignment PIN_T21 -to cpu_resetn
set_location_assignment PIN_AE5 -to ddr2bot_we_n
set_location_assignment PIN_AE21 -to ddr2bot_ras_n
set_location_assignment PIN_AD21 -to ddr2bot_cas_n
set_location_assignment PIN_AG4 -to ddr2bot_cke
set_location_assignment PIN_AC21 -to ddr2bot_cs_n
set_location_assignment PIN_AE24 -to ddr2bot_odt
set_location_assignment PIN_AG22 -to ddr2bot_dq[0]
set_location_assignment PIN_AH21 -to ddr2bot_dq[1]
set_location_assignment PIN_AH22 -to ddr2bot_dq[2]
set_location_assignment PIN_AG21 -to ddr2bot_dq[3]
set_location_assignment PIN_AD17 -to ddr2bot_dq[4]
set_location_assignment PIN_AH23 -to ddr2bot_dq[5]
set_location_assignment PIN_AE19 -to ddr2bot_dq[6]
set_location_assignment PIN_AF24 -to ddr2bot_dq[7]
set_location_assignment PIN_AG18 -to ddr2bot_dq[8]
set_location_assignment PIN_AG17 -to ddr2bot_dq[9]
set_location_assignment PIN_AH18 -to ddr2bot_dq[10]
set_location_assignment PIN_AH17 -to ddr2bot_dq[11]
set_location_assignment PIN_AF15 -to ddr2bot_dq[12]
set_location_assignment PIN_AE17 -to ddr2bot_dq[13]
set_location_assignment PIN_AF16 -to ddr2bot_dq[14]
set_location_assignment PIN_AB16 -to ddr2bot_dq[15]
set_location_assignment PIN_AE11 -to ddr2bot_dq[16]
set_location_assignment PIN_AG11 -to ddr2bot_dq[17]
set_location_assignment PIN_AG10 -to ddr2bot_dq[18]
set_location_assignment PIN_AH11 -to ddr2bot_dq[19]
set_location_assignment PIN_AE9 -to ddr2bot_dq[20]
set_location_assignment PIN_AE12 -to ddr2bot_dq[21]
set_location_assignment PIN_AF10 -to ddr2bot_dq[22]
set_location_assignment PIN_AE13 -to ddr2bot_dq[23]
set_location_assignment PIN_AC8 -to ddr2bot_dq[24]
set_location_assignment PIN_AH7 -to ddr2bot_dq[25]
set_location_assignment PIN_AG8 -to ddr2bot_dq[26]
set_location_assignment PIN_AH8 -to ddr2bot_dq[27]
set_location_assignment PIN_AG7 -to ddr2bot_dq[28]
set_location_assignment PIN_AA10 -to ddr2bot_dq[29]
set_location_assignment PIN_AF7 -to ddr2bot_dq[30]
set_location_assignment PIN_AD10 -to ddr2bot_dq[31]
set_location_assignment PIN_AE18 -to ddr2bot_dqs[0]
set_location_assignment PIN_AF17 -to ddr2bot_dqs[1]
set_location_assignment PIN_AF11 -to ddr2bot_dqs[2]
set_location_assignment PIN_AE10 -to ddr2bot_dqs[3]
set_location_assignment PIN_AH19 -to ddr2bot_dm[0]
set_location_assignment PIN_AC15 -to ddr2bot_dm[1]
set_location_assignment PIN_AF8 -to ddr2bot_dm[2]
set_location_assignment PIN_AB9 -to ddr2bot_dm[3]
set_location_assignment PIN_AE14 -to ddr2bot_clk
set_location_assignment PIN_AF14 -to ddr2bot_clk_n
set_location_assignment PIN_AB22 -to ddr2bot_addr[0]
set_location_assignment PIN_AG6 -to ddr2bot_addr[1]
set_location_assignment PIN_Y13 -to ddr2bot_addr[2]
set_location_assignment PIN_AE7 -to ddr2bot_addr[3]
set_location_assignment PIN_AB12 -to ddr2bot_addr[4]
set_location_assignment PIN_AC7 -to ddr2bot_addr[5]
set_location_assignment PIN_AD12 -to ddr2bot_addr[6]
set_location_assignment PIN_AB8 -to ddr2bot_addr[7]
set_location_assignment PIN_AH12 -to ddr2bot_addr[8]
set_location_assignment PIN_AB10 -to ddr2bot_addr[9]
set_location_assignment PIN_AE4 -to ddr2bot_addr[10]
set_location_assignment PIN_AF21 -to ddr2bot_addr[11]
set_location_assignment PIN_Y12 -to ddr2bot_addr[12]
set_location_assignment PIN_AF3 -to ddr2bot_ba[0]
set_location_assignment PIN_AF5 -to ddr2bot_ba[1]
set_location_assignment PIN_AA14 -to ddr2bot_active
set_location_assignment PIN_N8 -to enet_mdc
set_location_assignment PIN_L5 -to enet_mdio
set_location_assignment PIN_B14 -to enet_rx_clk
set_location_assignment PIN_AA7 -to enet_tx_en
set_location_assignment PIN_T8 -to enet_gtx_clk
set_location_assignment PIN_W8 -to enet_rxd[0]
set_location_assignment PIN_AA6 -to enet_rxd[1]
set_location_assignment PIN_W7 -to enet_rxd[2]
set_location_assignment PIN_Y6 -to enet_rxd[3]
set_location_assignment PIN_W4 -to enet_txd[0]
set_location_assignment PIN_AA5 -to enet_txd[1]
set_location_assignment PIN_Y5 -to enet_txd[2]
set_location_assignment PIN_W3 -to enet_txd[3]
set_location_assignment PIN_AB4 -to enet_rx_dv
set_location_assignment PIN_AD2 -to enet_resetn
set_location_assignment PIN_AC25 -to enet_led_link1000
set_location_assignment PIN_Y17 -to flash_oen
set_location_assignment PIN_AA21 -to flash_wen
set_location_assignment PIN_Y16 -to flash_cen
set_location_assignment PIN_AG25 -to flash_rdybsyn
set_location_assignment PIN_AB20 -to flash_resetn
set_location_assignment PIN_AC11 -to fsa[0]
set_location_assignment PIN_AH10 -to fsa[1]
set_location_assignment PIN_AA13 -to fsa[2]
set_location_assignment PIN_AC10 -to fsa[3]
set_location_assignment PIN_Y15 -to fsa[4]
set_location_assignment PIN_AF22 -to fsa[5]
set_location_assignment PIN_AF26 -to fsa[6]
set_location_assignment PIN_AF4 -to fsa[7]
set_location_assignment PIN_AD8 -to fsa[8]
set_location_assignment PIN_AG26 -to fsa[9]
set_location_assignment PIN_AH6 -to fsa[10]
set_location_assignment PIN_AD24 -to fsa[11]
set_location_assignment PIN_AF9 -to fsa[12]
set_location_assignment PIN_AA8 -to fsa[13]
set_location_assignment PIN_AC22 -to fsa[14]
set_location_assignment PIN_AE8 -to fsa[15]
set_location_assignment PIN_AF13 -to fsa[16]
set_location_assignment PIN_AB14 -to fsa[17]
set_location_assignment PIN_AF23 -to fsa[18]
set_location_assignment PIN_AG12 -to fsa[19]
set_location_assignment PIN_AB18 -to fsa[20]
set_location_assignment PIN_Y19 -to fsa[21]
set_location_assignment PIN_AG3 -to fsa[22]
set_location_assignment PIN_AE16 -to fsa[23]
set_location_assignment PIN_AB7 -to fsa[24]
set_location_assignment PIN_J14 -to fsd[0]
set_location_assignment PIN_D6 -to fsd[1]
set_location_assignment PIN_J17 -to fsd[2]
set_location_assignment PIN_G7 -to fsd[3]
set_location_assignment PIN_F18 -to fsd[4]
set_location_assignment PIN_C6 -to fsd[5]
set_location_assignment PIN_H17 -to fsd[6]
set_location_assignment PIN_C18 -to fsd[7]
set_location_assignment PIN_D18 -to fsd[8]
set_location_assignment PIN_G16 -to fsd[9]
set_location_assignment PIN_G22 -to fsd[10]
set_location_assignment PIN_F12 -to fsd[11]
set_location_assignment PIN_D11 -to fsd[12]
set_location_assignment PIN_E24 -to fsd[13]
set_location_assignment PIN_H21 -to fsd[14]
set_location_assignment PIN_G9 -to fsd[15]
set_location_assignment PIN_A4 -to fsd[16]
set_location_assignment PIN_G13 -to fsd[17]
set_location_assignment PIN_H14 -to fsd[18]
set_location_assignment PIN_B8 -to fsd[19]
set_location_assignment PIN_C8 -to fsd[20]
set_location_assignment PIN_F7 -to fsd[21]
set_location_assignment PIN_B11 -to fsd[22]
set_location_assignment PIN_B22 -to fsd[23]
set_location_assignment PIN_A18 -to fsd[24]
set_location_assignment PIN_G8 -to fsd[25]
set_location_assignment PIN_J12 -to fsd[26]
set_location_assignment PIN_D9 -to fsd[27]
set_location_assignment PIN_C9 -to fsd[28]
set_location_assignment PIN_E7 -to fsd[29]
set_location_assignment PIN_H10 -to fsd[30]
set_location_assignment PIN_J10 -to fsd[31]
set_location_assignment PIN_AD7 -to user_pb[0]
set_location_assignment PIN_AC12 -to user_pb[1]
set_location_assignment PIN_AH3 -to user_pb[2]
set_location_assignment PIN_AA12 -to user_pb[3]
set_location_assignment PIN_AC14 -to user_dipsw[0]
set_location_assignment PIN_AD18 -to user_dipsw[1]
set_location_assignment PIN_AG23 -to user_dipsw[2]
set_location_assignment PIN_AC19 -to user_dipsw[3]
set_location_assignment PIN_AD14 -to user_dipsw[4]
set_location_assignment PIN_G20 -to user_dipsw[5]
set_location_assignment PIN_AB15 -to user_dipsw[6]
set_location_assignment PIN_AF25 -to user_dipsw[7]
set_location_assignment PIN_AD15 -to user_led[0]
set_location_assignment PIN_AE20 -to user_led[1]
set_location_assignment PIN_AF18 -to user_led[2]
set_location_assignment PIN_AD19 -to user_led[3]
set_location_assignment PIN_AE15 -to user_led[4]
set_location_assignment PIN_AC17 -to user_led[5]
set_location_assignment PIN_AG19 -to user_led[6]
set_location_assignment PIN_AF19 -to user_led[7]
set_location_assignment PIN_Y26 -to hsmb_tx_d_n[10]
set_location_assignment PIN_AA25 -to hsmb_tx_d_p[11]

# Fitter Assignments
# ==================
set_instance_assignment -name IO_STANDARD "1.8 V" -to clkin_50
set_instance_assignment -name IO_STANDARD "1.8 V" -to clkin_125
set_instance_assignment -name IO_STANDARD "1.8 V" -to ddr2bot_active
set_instance_assignment -name IO_STANDARD "1.8 V" -to enet_rx_clk
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_led_link1000
set_instance_assignment -name IO_STANDARD "1.8 V" -to flash_oen
set_instance_assignment -name IO_STANDARD "1.8 V" -to flash_wen
set_instance_assignment -name IO_STANDARD "1.8 V" -to flash_cen
set_instance_assignment -name IO_STANDARD "1.8 V" -to flash_rdybsyn
set_instance_assignment -name IO_STANDARD "1.8 V" -to flash_resetn
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_odt
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_clk
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_clk_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_cs_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_cke
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_addr[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_addr[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_addr[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_addr[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_addr[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_addr[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_addr[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_addr[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_addr[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_addr[9]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_addr[10]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_addr[11]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_addr[12]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_ba[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_ba[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_ras_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_cas_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_we_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[9]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[10]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[11]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[12]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[13]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[14]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[15]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[16]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[17]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[18]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[19]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[20]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[21]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[22]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[23]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[24]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[25]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[26]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[27]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[28]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[29]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[30]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dq[31]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dqs[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dqs[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dqs[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dqs[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dm[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dm[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dm[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to ddr2bot_dm[3]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_dipsw[7]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_dipsw[6]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_dipsw[5]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_dipsw[4]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_dipsw[3]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_dipsw[2]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_dipsw[1]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_dipsw[0]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_pb[3]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_pb[2]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_pb[1]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_pb[0]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[31]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[30]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[29]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[28]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[27]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[26]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[25]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[24]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[23]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[22]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[21]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[20]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[19]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[18]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[17]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[16]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[15]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[14]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[13]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[12]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[11]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[10]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[9]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[8]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[7]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[6]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[5]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[4]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[3]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[2]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[1]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsd[0]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[24]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[23]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[22]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[21]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[20]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[19]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[18]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[17]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[16]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[15]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[14]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[13]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[12]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[11]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[10]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[9]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[8]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[7]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[6]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[5]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[4]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[3]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[2]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[1]
set_instance_assignment -name IO_STANDARD "1.8 V" -to fsa[0]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_led[7]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_led[6]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_led[5]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_led[4]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_led[3]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_led[2]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_led[1]
set_instance_assignment -name IO_STANDARD "1.8 V" -to user_led[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to cpu_resetn
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_resetn
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_rx_dv
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_txd[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_txd[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_txd[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_txd[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_rxd[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_rxd[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_rxd[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_rxd[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_gtx_clk
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_tx_en
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_mdio
set_instance_assignment -name IO_STANDARD "2.5 V" -to enet_mdc
set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmb_tx_d_p[11]
set_instance_assignment -name IO_STANDARD "2.5 V" -to hsmb_tx_d_n[10]
set_instance_assignment -name IO_MAXIMUM_TOGGLE_RATE "0 MHz" -to cpu_resetn
set_instance_assignment -name IO_MAXIMUM_TOGGLE_RATE "0 MHz" -to enet_mdc
set_instance_assignment -name IO_MAXIMUM_TOGGLE_RATE "0 MHz" -to enet_mdio
set_instance_assignment -name IO_MAXIMUM_TOGGLE_RATE "0 MHz" -to enet_resetn
set_instance_assignment -name IO_MAXIMUM_TOGGLE_RATE "0 MHz" -to flash_resetn
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_odt
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_clk
set_instance_assignment -name PAD_TO_CORE_DELAY 0 -to ddr2bot_clk
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_clk_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_cs_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_cke
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_addr[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_addr[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_addr[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_addr[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_addr[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_addr[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_addr[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_addr[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_addr[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_addr[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_addr[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_addr[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_addr[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_ba[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_ba[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_ras_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_cas_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to ddr2bot_we_n
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[13]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[14]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[15]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[16]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[17]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[18]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[19]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[20]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[21]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[22]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[23]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[24]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[25]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[26]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[27]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[28]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[29]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[30]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dq[31]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dqs[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dqs[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dqs[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dqs[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dm[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dm[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dm[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to ddr2bot_dm[3]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[2]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[3]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[4]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[5]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[6]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[7]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[8]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[9]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[10]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[11]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[12]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[13]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[14]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[15]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[16]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[17]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[18]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[19]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[20]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[21]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[22]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[23]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[24]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[25]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[26]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[27]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[28]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[29]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[30]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dq[31]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dqs[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dqs[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dqs[2]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dqs[3]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dm[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dm[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dm[2]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 253960908 -to ddr2bot_dm[3]
set_instance_assignment -name CKN_CK_PAIR ON -from ddr2bot_clk_n -to ddr2bot_clk
set_instance_assignment -name SLEW_RATE 0 -to user_led[7]
set_instance_assignment -name SLEW_RATE 0 -to user_led[0]
set_instance_assignment -name SLEW_RATE 0 -to user_led[1]
set_instance_assignment -name SLEW_RATE 0 -to user_led[2]
set_instance_assignment -name SLEW_RATE 0 -to user_led[3]
set_instance_assignment -name SLEW_RATE 0 -to user_led[4]
set_instance_assignment -name SLEW_RATE 0 -to user_led[5]
set_instance_assignment -name SLEW_RATE 0 -to user_led[6]
set_instance_assignment -name SLEW_RATE 0 -to hsmb_tx_d_p[11]
set_instance_assignment -name SLEW_RATE 2 -to fsd[0]
set_instance_assignment -name SLEW_RATE 2 -to fsd[1]
set_instance_assignment -name SLEW_RATE 2 -to fsd[2]
set_instance_assignment -name SLEW_RATE 2 -to fsd[3]
set_instance_assignment -name SLEW_RATE 2 -to fsd[4]
set_instance_assignment -name SLEW_RATE 2 -to fsd[5]
set_instance_assignment -name SLEW_RATE 2 -to fsd[6]
set_instance_assignment -name SLEW_RATE 2 -to fsd[7]
set_instance_assignment -name SLEW_RATE 2 -to fsd[8]
set_instance_assignment -name SLEW_RATE 2 -to fsd[9]
set_instance_assignment -name SLEW_RATE 2 -to fsd[10]
set_instance_assignment -name SLEW_RATE 2 -to fsd[11]
set_instance_assignment -name SLEW_RATE 2 -to fsd[12]
set_instance_assignment -name SLEW_RATE 2 -to fsd[13]
set_instance_assignment -name SLEW_RATE 2 -to fsd[14]
set_instance_assignment -name SLEW_RATE 2 -to fsd[15]
set_instance_assignment -name SLEW_RATE 2 -to fsd[16]
set_instance_assignment -name SLEW_RATE 2 -to fsd[17]
set_instance_assignment -name SLEW_RATE 2 -to fsd[18]
set_instance_assignment -name SLEW_RATE 2 -to fsd[19]
set_instance_assignment -name SLEW_RATE 2 -to fsd[20]
set_instance_assignment -name SLEW_RATE 2 -to fsd[21]
set_instance_assignment -name SLEW_RATE 2 -to fsd[22]
set_instance_assignment -name SLEW_RATE 2 -to fsd[23]
set_instance_assignment -name SLEW_RATE 2 -to fsd[24]
set_instance_assignment -name SLEW_RATE 2 -to fsd[25]
set_instance_assignment -name SLEW_RATE 2 -to fsd[26]
set_instance_assignment -name SLEW_RATE 2 -to fsd[27]
set_instance_assignment -name SLEW_RATE 2 -to fsd[28]
set_instance_assignment -name SLEW_RATE 2 -to fsd[29]
set_instance_assignment -name SLEW_RATE 2 -to fsd[30]
set_instance_assignment -name SLEW_RATE 2 -to fsd[31]
set_instance_assignment -name SLEW_RATE 2 -to fsa[0]
set_instance_assignment -name SLEW_RATE 2 -to fsa[1]
set_instance_assignment -name SLEW_RATE 2 -to fsa[2]
set_instance_assignment -name SLEW_RATE 2 -to fsa[3]
set_instance_assignment -name SLEW_RATE 2 -to fsa[4]
set_instance_assignment -name SLEW_RATE 2 -to fsa[5]
set_instance_assignment -name SLEW_RATE 2 -to fsa[6]
set_instance_assignment -name SLEW_RATE 2 -to fsa[7]
set_instance_assignment -name SLEW_RATE 2 -to fsa[8]
set_instance_assignment -name SLEW_RATE 2 -to fsa[9]
set_instance_assignment -name SLEW_RATE 2 -to fsa[10]
set_instance_assignment -name SLEW_RATE 2 -to fsa[11]
set_instance_assignment -name SLEW_RATE 2 -to fsa[12]
set_instance_assignment -name SLEW_RATE 2 -to fsa[13]
set_instance_assignment -name SLEW_RATE 2 -to fsa[14]
set_instance_assignment -name SLEW_RATE 2 -to fsa[15]
set_instance_assignment -name SLEW_RATE 2 -to fsa[16]
set_instance_assignment -name SLEW_RATE 2 -to fsa[17]
set_instance_assignment -name SLEW_RATE 2 -to fsa[18]
set_instance_assignment -name SLEW_RATE 2 -to fsa[19]
set_instance_assignment -name SLEW_RATE 2 -to fsa[20]
set_instance_assignment -name SLEW_RATE 2 -to fsa[21]
set_instance_assignment -name SLEW_RATE 2 -to fsa[22]
set_instance_assignment -name SLEW_RATE 2 -to fsa[23]
set_instance_assignment -name SLEW_RATE 2 -to fsa[24]
set_instance_assignment -name SLEW_RATE 2 -to flash_wen
set_instance_assignment -name SLEW_RATE 2 -to flash_resetn
set_instance_assignment -name SLEW_RATE 2 -to flash_oen
set_instance_assignment -name SLEW_RATE 2 -to flash_cen
set_instance_assignment -name SLEW_RATE 2 -to enet_txd[0]
set_instance_assignment -name SLEW_RATE 2 -to enet_txd[1]
set_instance_assignment -name SLEW_RATE 2 -to enet_txd[2]
set_instance_assignment -name SLEW_RATE 2 -to enet_txd[3]
set_instance_assignment -name SLEW_RATE 2 -to enet_tx_en
set_instance_assignment -name SLEW_RATE 2 -to enet_resetn
set_instance_assignment -name SLEW_RATE 2 -to enet_mdio
set_instance_assignment -name SLEW_RATE 2 -to enet_mdc
set_instance_assignment -name SLEW_RATE 2 -to enet_gtx_clk
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_we_n
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_ras_n
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_odt
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dqs[0]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dqs[1]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dqs[2]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dqs[3]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[0]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[1]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[2]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[3]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[4]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[5]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[6]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[7]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[8]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[9]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[10]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[11]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[12]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[13]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[14]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[15]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[16]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[17]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[18]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[19]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[20]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[21]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[22]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[23]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[24]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[25]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[26]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[27]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[28]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[29]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[30]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dq[31]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dm[0]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dm[1]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dm[2]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_dm[3]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_cs_n
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_clk_n
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_clk
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_cke
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_cas_n
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_ba[0]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_ba[1]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_addr[0]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_addr[1]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_addr[2]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_addr[3]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_addr[4]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_addr[5]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_addr[6]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_addr[7]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_addr[8]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_addr[9]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_addr[10]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_addr[11]
set_instance_assignment -name SLEW_RATE 2 -to ddr2bot_addr[12]
set_instance_assignment -name SLEW_RATE 0 -to ddr2bot_active
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to enet_mdio
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[31]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[30]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[29]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[28]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[27]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[26]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[25]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[24]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[23]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[22]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[21]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[20]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[19]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[18]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[17]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[16]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[15]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[14]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[13]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsd[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to ddr2bot_active
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to enet_gtx_clk
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to enet_mdc
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to enet_resetn
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to enet_tx_en
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to enet_txd[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to enet_txd[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to enet_txd[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to enet_txd[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to flash_cen
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to flash_oen
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to flash_resetn
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to flash_wen
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[24]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[23]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[22]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[21]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[20]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[19]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[18]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[17]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[16]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[15]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[14]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[13]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to fsa[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to hsmb_tx_d_p[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to user_led[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to user_led[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to user_led[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to user_led[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to user_led[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to user_led[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to user_led[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to user_led[0]
